### PR TITLE
Add websockets as an internal module

### PR DESCRIPTION
**Pull request by matthewloring**
This incorporates websockets (source: npm.im/ws) as well as its dependencies ultron (source: npm.im/ultron) and options (source: npm.im/options).

### CODE REVIEW

**Comment by ofrobots** [comment]
How would we track which version of ws, ultron, etc. (e.g. released version, git sha, etc.) has been imported? A few more questions
* it seems like `ws` and its dependencies (e.g. `ultron`) are smooshed into the same directory. Would it possible to keep them separated?
* it is suboptimal that we have vendored third_party code living in the lib/ directory. Is there any way we could have the code live in `deps/` but be able to `require` it internally? The main challenge here is probably the fact that code in `lib` gets `js2c`-compiled into the node binary. Perhaps we can modify the install process to install `ws`, `ultron` et. al. on the target system, and then modify `require` to support a special syntax (say `require('internal/vendor/ws')`) that knows how to pick up the dependency from the install directory? Food for thought.

**Comment by matthewloring** [comment]
We could track versions with a `versions` file or leave a package.json in place (with a bunch of info stripped out). We can definitely keep these packages separated. My hope with smooshing them would be to simplify the upgrade script but I guess if it's scripted the complexity is a one time cost. Do you want to preserve the directory structure from the modules themselves or just separate all the flattened source into separate top level directories.

The concern I had with including the code in deps is properly shielding it from user space. Does namespacing with `internal/vendor` satisfy the requirement of keeping it internal? The benefit of approaches that put the code somewhere in lib is that it can be completely inaccessible to user space while being loaded by other library modules. I can definitely figure out the namespaced approach if it is sufficient from a visibility standpoint.

**Comment by ofrobots** [comment]
Keeping the files from different packages separated makes it easier to track pedigree of the files.

Upon reflection, I also have concerns about shielding deps from user space. It would be much nicer to have `ws` and dependencies statically linked into the node binary.

**Comment by repenaxa** [comment]
@ofrobots: I trust you with incorporating this into Node, but I have a vague recollection of Node's willingness to implement it in native. It is also a weird move to fuse a third party dep into the core.

**Comment by ofrobots** [comment]
@repenaxa At this point there is no active proposal for a native implementation of websockets in core.  Bringing in `ws` into core does look weird indeed. But we wanted to explore what the path looks like, if this ends up being the path of least resistance.

**Comment by matthewloring** [comment]
Closing in favor of #3

**Pull request closed without merging**
