### PR TITLE
Bring websockets in through deps

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots This is an example of how ws could be included from deps. It does not prevent access by userspace modules (looking into how this might be accomplished).

**Comment by matthewloring** [comment]
@ofrobots, the most recent iteration is properly shielded from userspace modules.

**Comment by ofrobots** [comment]
Do we need `ws` (and others0 to be in `deps/vendor/ws`? `vendor` and `deps` are synonyms. Could you move these one directory up?

I do think it is important to have `vendor` in the require syntax: `require('vendor/ws/index').Server;`, but I don't think we need a `deps/vendor` directory.

**Comment by ofrobots** [comment]
On second thought, I don't think it is important to have `vendor` in the require syntax.

**Comment by ofrobots** [comment]
Rename `README.vendor` to `README.node`.

**Comment by matthewloring** [comment]
@ofrobots Addressed the comments.

**Comment by ofrobots** [comment]
LGTM.

**Comment by matthewloring** [comment]
Landed in 23eb1c2f3d05a6b691ec4778f3ed6be1f51dd807.

**Pull request closed without merging**
